[project]
name = "gaida-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "verba-neo", email = "verba.it.corp@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
