[project]
name = "gaida-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "verba-neo", email = "verba.it.corp@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "flask>=3.1.3",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "langchain>=1.3.18",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-openai>=1.6.0",
    "matplotlib>=3.11.1",
    "openai>=3.5.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
]


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
