[project]
name = "11-eval-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "langchain>=1.3.18",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "langgraph-cli[inmem]>=0.4.31",
]
