[project]
name = "langgraph-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.1",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "langgraph-cli[inmem]>=0.4.31",
    "pypdf>=6.18.0",
]
